spring.application.name=backend-java

# URL de ligação ao PostgreSQL na Azure
spring.datasource.url=jdbc:postgresql://data-gear.postgres.database.azure.com:5432/postgres?sslmode=require

# Nome de utilizador (Logon do administrador na imagem)
spring.datasource.username=brunopereira

# Palavra-passe definida quando criaste o servidor na Azure
spring.datasource.password=${DB_PASSWORD}

# Driver PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect